[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[k3s_nodes]
k3s-server-1 ansible_host=192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/k3s_ansible_key

[grafana]
grafana1 ansible_host=192.168.56.11 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/k3s_ansible_key