name: Configure Infrastructure with Ansible

on:
    push:
        branches:
            - main

jobs:
    infra:
        name: Provision & Configure VMs
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  clean: false

            - name: Create ssh_keys directory and copy public key
              env:
                  SSH_PUB_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
              run: |
                  New-Item -ItemType Directory -Force -Path ssh_keys
                  Set-Content -Path "ssh_keys\k3s_ansible_key.pub" -Value $env:SSH_PUB_KEY

            - name: Vagrant Up
              run: |
                  vagrant up

            - name: Copy SSH Secret Key to WSL
              env:
                  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  wsl mkdir -p ~/.ssh
                  $env:SSH_KEY | wsl tee ~/.ssh/k3s_ansible_key > $null
                  wsl sed -i 's/\r$//' ~/.ssh/k3s_ansible_key
                  wsl chmod 600 ~/.ssh/k3s_ansible_key

            - name: Ansible playbook for k3s installation
              run: |
                  wsl ansible-playbook -i ansible/inventory.ini ansible/k3s-install.yaml

    build-and-push:
        runs-on: self-hosted
        needs: infra
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to DockerHub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              run: |
                  docker build -t clmtm/devops_final:latest .
                  docker push clmtm/devops_final:latest

    deploy-app:
        runs-on: self-hosted
        needs: build-and-push
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Apply K8s Manifests (via WSL)
              run: |
                  wsl kubectl apply -f k8s/
                  wsl kubectl rollout restart deployment api-lacet
